import { useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, ChevronRight, Search, Stethoscope } from "lucide-react";

type Doctor = { id:string; name:string; title:string; specialty:string; hospital:string };
type Hospital = { id:string; name:string; grade:string; campuses:string[]; departments:string[]; doctors:Record<string,Doctor[]> };
type City = { hospitals:Hospital[] };
type Page = "home"|"hospital"|"campus"|"department"|"doctor"|"slots"|"done";

const mock:Record<string,City> = {
  "深圳市": { hospitals:[
    {id:"sz-rm",name:"深圳市人民医院",grade:"三级甲等",campuses:["留医部"],departments:["内科","外科","儿科","骨科"],doctors:{"内科":[{id:"SZ001",name:"张医生",title:"主任医师",specialty:"心血管内科",hospital:"深圳市人民医院"},{id:"SZ002",name:"李医生",title:"副主任医师",specialty:"呼吸内科",hospital:"深圳市人民医院"}],"外科":[{id:"SZ003",name:"陈医生",title:"主任医师",specialty:"普外科",hospital:"深圳市人民医院"}],"儿科":[],"骨科":[]}},
    {id:"sz-child",name:"深圳市儿童医院",grade:"三级甲等",campuses:["总院"],departments:["儿科","内科"],doctors:{"儿科":[{id:"SZ101",name:"赵医生",title:"主任医师",specialty:"儿童呼吸",hospital:"深圳市儿童医院"}],"内科":[]}}
  ]},
  "上海市": { hospitals:[{id:"sh-rm",name:"上海市第一人民医院",grade:"三级甲等",campuses:["北部院区","南部院区"],departments:["内科","外科","妇产科"],doctors:{"内科":[{id:"SH001",name:"吴医生",title:"副主任医师",specialty:"呼吸内科",hospital:"上海市第一人民医院"}],"外科":[],"妇产科":[]}}]},
  "北京市": { hospitals:[{id:"bj-xh",name:"北京协和医院",grade:"三级甲等",campuses:["东单院区"],departments:["内科","外科","骨科"],doctors:{"内科":[{id:"BJ001",name:"孙医生",title:"主任医师",specialty:"内分泌科",hospital:"北京协和医院"}],"外科":[],"骨科":[]}}]}
};
const dates=["今天 8/17","明天 8/18","周三 8/19","周四 8/20","周五 8/21"];
const slots=["08:00","08:30","09:00","09:30","10:00","10:30","14:00","14:30","15:00"];

export default function App(){
  const [page,setPage]=useState<Page>("home"),[city]=useState("深圳市"),[hospital,setHospital]=useState<Hospital|null>(null),[campus,setCampus]=useState(""),[department,setDepartment]=useState(""),[doctor,setDoctor]=useState<Doctor|null>(null),[date,setDate]=useState(dates[0]),[slot,setSlot]=useState(""),[query,setQuery]=useState("");
  const hospitals=mock[city].hospitals;
  const doctors=useMemo(()=>department&&hospital?hospital.doctors[department]??[]:[],[hospital,department]);
  const filteredHospitals=hospitals.filter(h=>!query||h.name.includes(query));
  const chooseHospital=(h:Hospital)=>{setHospital(h);setCampus(h.campuses.length>1?"":h.campuses[0]);setPage(h.campuses.length>1?"campus":"department")};
  const back=()=>{if(page==="hospital")setPage("home");else if(page==="campus")setPage("hospital");else if(page==="department")setPage(hospital&&hospital.campuses.length>1?"campus":"hospital");else if(page==="doctor")setPage("department");else if(page==="slots")setPage("doctor")};
  const reset=()=>{setPage("home");setHospital(null);setCampus("");setDepartment("");setDoctor(null);setSlot("");setQuery("")};
  const title=page==="home"?"科室挂号":page==="hospital"?"选择医院":page==="campus"?"选择院区":page==="department"?"选择科室":page==="doctor"?"选择医生":page==="slots"?"选择日期/号源":"挂号成功";
  return <div className="min-h-screen bg-[#f7f8fa] text-[#1d1b20] flex justify-center"><div className="w-full max-w-[430px] min-h-screen bg-white shadow-sm">
    <header className="h-14 px-5 flex items-center gap-3 border-b border-[#eee] bg-white sticky top-0 z-10">{page!=="home"&&page!=="done"?<button onClick={back} className="p-1 -ml-1"><ArrowLeft size={21}/></button>:null}<div className="flex-1"><div className="text-[18px] font-semibold">{title}</div>{page!=="home"&&hospital?<div className="text-[11px] text-[#79747e] mt-0.5">{hospital.name}</div>:null}</div>{page!=="done"?<div className="text-[13px] text-[#6750a4]">{city}</div>:null}</header>
    {page==="home"&&<main className="p-5"><div className="pt-5 pb-6"><div className="text-[28px] font-semibold leading-9">找到合适的医院和医生</div><div className="text-[14px] text-[#79747e] mt-2">按城市 → 医院 → 科室快速完成挂号</div></div><button onClick={()=>setPage("hospital")} className="w-full h-14 rounded-[28px] bg-[#f2edf7] flex items-center gap-3 px-5 text-left"><Search size={20} className="text-[#6750a4]"/><span className="text-[15px] text-[#49454f]">搜索医院、科室或医生</span></button><div className="mt-8 flex items-center justify-between"><div className="text-[18px] font-semibold">热门医院</div><button onClick={()=>setPage("hospital")} className="text-[13px] text-[#6750a4]">查看全部</button></div><div className="mt-3 space-y-3">{hospitals.map(h=><button key={h.id} onClick={()=>chooseHospital(h)} className="w-full p-4 rounded-3xl bg-white border border-[#e6e1e5] text-left flex items-center gap-4"><div className="w-11 h-11 rounded-2xl bg-[#f2edf7] flex items-center justify-center text-[#6750a4]"><Stethoscope size={21}/></div><div className="flex-1"><div className="font-medium text-[15px]">{h.name}</div><div className="text-[12px] text-[#79747e] mt-1">{h.grade} · {h.departments.length} 个科室</div></div><ChevronRight size={18} className="text-[#79747e]"/></button>)}</div></main>}
    {page==="hospital"&&<main className="p-5"><div className="relative mb-5"><Search size={18} className="absolute left-4 top-3.5 text-[#79747e]"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索医院" className="w-full h-12 rounded-2xl bg-[#f7f2fa] pl-11 pr-4 outline-none text-[14px]"/></div><div>{filteredHospitals.map(h=><button key={h.id} onClick={()=>chooseHospital(h)} className="w-full p-4 border-b border-[#eee] text-left flex items-center"><div className="flex-1"><div className="font-medium">{h.name}</div><div className="text-[12px] text-[#79747e] mt-1">{h.grade} · {h.campuses.length} 个院区</div></div><ChevronRight size={18} className="text-[#79747e]"/></button>)}</div></main>}
    {page==="campus"&&<main className="p-5"><div className="text-[13px] text-[#79747e] mb-3">请选择就诊院区</div>{hospital?.campuses.map(c=><button key={c} onClick={()=>{setCampus(c);setPage("department")}} className="w-full p-4 mb-2 rounded-2xl border border-[#e6e1e5] text-left flex items-center justify-between"><span className="font-medium">{c}</span><ChevronRight size={18}/></button>)}</main>}
    {page==="department"&&<main className="p-5"><div className="text-[13px] text-[#79747e] mb-3">{campus?`就诊院区：${campus}`:"请选择科室"}</div><div className="grid grid-cols-2 gap-3">{hospital?.departments.map(d=><button key={d} onClick={()=>{setDepartment(d);setPage("doctor")}} className="min-h-20 p-4 rounded-2xl border border-[#e6e1e5] text-left flex items-end justify-between"><span className="font-medium">{d}</span><ChevronRight size={17} className="text-[#79747e]"/></button>)}</div></main>}
    {page==="doctor"&&<main className="p-5"><div className="mb-5"><div className="text-[18px] font-semibold">{department}</div><div className="text-[12px] text-[#79747e] mt-1">{hospital?.name}{campus?` · ${campus}`:""}</div></div>{doctors.length?<div className="space-y-2">{doctors.map(d=><button key={d.id} onClick={()=>{setDoctor(d);setPage("slots")}} className="w-full p-4 rounded-2xl border border-[#e6e1e5] text-left flex items-center gap-3"><div className="w-11 h-11 rounded-full bg-[#f2edf7] flex items-center justify-center text-[#6750a4]"><Stethoscope size={20}/></div><div className="flex-1"><div className="font-medium">{d.name} <span className="text-[12px] text-[#79747e] ml-1">{d.title}</span></div><div className="text-[12px] text-[#79747e] mt-1">{d.specialty}</div></div><ChevronRight size={18}/></button>)}</div>:<div className="py-20 text-center text-[#79747e]">当前科室暂无可预约医生</div>}</main>}
    {page==="slots"&&<main className="p-5"><div className="p-4 rounded-2xl bg-[#f7f2fa] mb-5"><div className="font-medium">{doctor?.name} · {doctor?.title}</div><div className="text-[12px] text-[#79747e] mt-1">{doctor?.specialty} · {hospital?.name}</div></div><div className="flex gap-2 overflow-x-auto pb-2 mb-5">{dates.map(d=><button key={d} onClick={()=>setDate(d)} className={`shrink-0 px-4 py-2.5 rounded-2xl text-[13px] ${date===d?"bg-[#6750a4] text-white":"bg-[#f7f2fa] text-[#49454f]"}`}>{d}</button>)}</div><div className="flex items-center gap-2 mb-3 text-[15px] font-semibold"><CalendarDays size={18}/>可预约号源</div><div className="grid grid-cols-3 gap-2">{slots.map(s=><button key={s} onClick={()=>setSlot(s)} className={`h-11 rounded-xl border text-[13px] ${slot===s?"border-[#6750a4] bg-[#f2edf7] text-[#6750a4]":"border-[#e6e1e5]"}`}>{s}</button>)}</div><button disabled={!slot} onClick={()=>setPage("done")} className="w-full h-12 mt-8 rounded-2xl bg-[#6750a4] text-white font-medium disabled:opacity-40">确认挂号</button></main>}
    {page==="done"&&<main className="p-7 text-center"><div className="w-16 h-16 mx-auto mt-14 rounded-full bg-[#e8f5e9] flex items-center justify-center text-[#2e7d32] text-3xl">✓</div><div className="text-[24px] font-semibold mt-6">挂号成功</div><div className="text-[14px] text-[#79747e] mt-3">{hospital?.name} · {department}</div><div className="text-[14px] text-[#79747e] mt-1">{doctor?.name} · {date} · {slot}</div><button onClick={reset} className="w-full h-12 mt-8 rounded-2xl bg-[#6750a4] text-white font-medium">返回首页</button></main>}
  </div></div>;
}
